"""
RAG Service  –  Phase 5 (Basic RAG Pipeline), routed by Phase 8, fused by Phase 9,
                 generated by Phase 10, verified by Phase 11
------------------------------------------------------------------------------------
Implements the end-to-end Retrieval-Augmented Generation chain:

  User Question
       ↓
  Query Intelligence  (Phase 7 – intent/entities/complexity/temporal)
       ↓
  Adaptive Retrieval Router  (Phase 8 – vector | BM25 | graph | hybrid)
       ↓
  Context Fusion  (Phase 9 – dedup → cross-encoder rerank → compress → prompt)
       ↓
  Enterprise LLM  (Phase 10 – Llama 3 / Gemma / Mistral / Qwen / OpenAI / Groq)
       ↓
  Evidence Verification  (Phase 11 – claim extraction → re-retrieval →
                           fact verification → confidence → hallucination
                           detection → rewrite)
       ↓
  Verified, Grounded Answer + Citations
       ↓
  Query Log  (Phase 12 – route/model/confidence/latency telemetry, so
              Continuous Learning's Performance Metrics + Improve
              Routing/Retrieval have something to learn from)

Entry point: answer_question(db, query, top_k, document_id_filter, model)
"""
from __future__ import annotations

import logging
import time
from typing import List, Optional

from sqlalchemy.orm import Session

from app.core.permissions import Role
from app.models.user import User
from app.services.vector_store import get_vector_store
from app.services.query_intelligence_service import QueryAnalysis, analyze_query
from app.services.adaptive_retrieval_service import AdaptiveRetrievalResult, adaptive_retrieve
from app.services.chunk_access_service import ChunkAccessContext, build_chunk_access_context
from app.services.context_fusion_service import ContextFusionResult, fuse_context
from app.services.enterprise_llm_service import GeneratedAnswer, generate_answer
from app.services.evidence_verification_service import VerificationResult, verify_answer
from app.services.query_log_service import log_query, new_query_id
from app.services.ticket_service import maybe_create_ticket
from app.core.config import settings

logger = logging.getLogger(__name__)


# ── Main RAG function ──────────────────────────────────────────────────────────

async def answer_question(
    db: Session,
    query: str,
    current_user: User,
    caller_role: Role,
    top_k: int = 5,
    document_id: Optional[str] = None,
    score_threshold: float = 0.0,
    model: Optional[str] = None,
) -> dict:
    """
    Execute the full RAG pipeline for a user question.

    Args:
        db:               Active SQLAlchemy session (BM25/graph retrieval need it).
        query:            The natural-language question to answer.
        current_user:     Authenticated caller (required — POST /rag/query has
                          required auth since the RBAC Foundation phase).
                          Recorded on any ticket this query raises, so
                          GET /tickets can scope "my tickets" for roles
                          without TICKET_ASSIGN/TICKET_RESOLVE.
        caller_role:      Authenticated caller's role. Together with
                          current_user, this builds the
                          chunk_access_service.ChunkAccessContext that gates
                          EVERY chunk this request can possibly see — see
                          Step 1 below. This is a security-critical
                          parameter: there is no default, so a caller
                          cannot accidentally omit it and retrieve
                          unscoped.
        top_k:            Maximum number of chunks to retrieve.
        document_id:      If set, filters results to chunks from that document only.
        score_threshold:  Minimum retriever score to include a chunk (0.0 = no filter).
        model:             Optional LLM override ("llama3"/"gemma"/"mistral"/"qwen"
                          or a raw Ollama tag); ignored for OpenAI/Groq providers.

    Returns:
        A dict with keys: answer, sources, total_indexed, retrieved_chunks,
        query_analysis, retrieval_route, context_fusion, model_used, grounding,
        verification, query_id.
    """
    query_id = new_query_id()
    started_at = time.perf_counter()
    logger.info(
        "[RAG] %s Query='%s...' top_k=%d doc_filter=%s user=%s role=%s",
        query_id, query[:60], top_k, document_id, current_user.email, caller_role.value,
    )

    # ─── Step 0b: Domain-Aware Chunk Access Control ───────────────────────────
    # Built once per request, threaded through every retrieval/re-retrieval
    # call below — see app/services/chunk_access_service.py.
    access_ctx: ChunkAccessContext = build_chunk_access_context(db, current_user, caller_role)

    # ─── Step 0: Query Intelligence (Phase 7 – Module 5) ──────────────────────
    # Parses/normalizes the question, detects intent, entities, complexity and
    # temporal scope, and widens retrieval breadth for medium/complex queries
    # (e.g. comparison questions spanning a date range need more evidence).
    analysis: QueryAnalysis = await analyze_query(query, default_top_k=top_k)
    effective_top_k = analysis.suggested_top_k

    store = get_vector_store()
    if store.total == 0:
        logger.warning("[RAG] Knowledge base is empty – no documents ingested yet.")
        return {
            "answer": (
                "The knowledge base is empty. Please upload documents before asking questions."
            ),
            "sources": [],
            "total_indexed": 0,
            "retrieved_chunks": 0,
            "query": query,
            "query_id": query_id,
            "query_analysis": analysis,
            "retrieval_route": None,
            "context_fusion": None,
            "model_used": None,
            "grounding": None,
            "verification": None,
        }

    # ─── Step 1: Adaptive Retrieval (Phase 8 – Module 6) ──────────────────────
    # The Router picks vector / BM25 / graph / hybrid based on the Phase 7
    # analysis (fact→vector, exact policy number→BM25, relationship→graph,
    # complex/comparison→hybrid RRF of all three).
    retrieval: AdaptiveRetrievalResult = adaptive_retrieve(
        db, analysis, top_k=effective_top_k, access_ctx=access_ctx, document_id=document_id
    )
    raw_results: List[dict] = retrieval.results

    # ─── Step 2: Filter by score threshold ────────────────────────────────────
    if score_threshold > 0.0:
        raw_results = [r for r in raw_results if r.get("score", 0.0) >= score_threshold]

    raw_results = raw_results[:effective_top_k]

    logger.info(
        "[RAG] Retrieved %d chunks via route=%s.", len(raw_results), retrieval.route.route
    )

    # ─── Steps 3-6: Context Fusion (Phase 9 – Module 7) ───────────────────────
    # Duplicate Removal → Cross Encoder Ranking → Context Compression →
    # Prompt Builder → Optimized Context. Overlapping/duplicate chunks are
    # dropped, the survivors are precisely rescored by a cross-encoder, trimmed
    # to their most relevant sentences, and fit into the context budget.
    fusion: ContextFusionResult = fuse_context(analysis.normalized_query, raw_results)
    fused_results = fusion.results

    logger.info(
        "[RAG] Sending prompt to LLM (context_chars=%d)...",
        len(fusion.prompt.optimized_context),
    )

    # ─── Step 7: Enterprise LLM generation (Phase 10 – Module 8) ──────────────
    # Prompt → LLM (Llama 3/Gemma/Mistral/Qwen via Ollama, or OpenAI/Groq) →
    # Grounded Answer → Citations. RuntimeError propagates unchanged so the
    # API layer keeps returning its existing 502 on LLM failures.
    generated: GeneratedAnswer = await generate_answer(
        fusion.prompt, fused_results, model=model
    )
    answer_text = generated.answer
    logger.info("[RAG] LLM response received (chars=%d).", len(answer_text))

    # ─── Step 8: Evidence Verification (Phase 11 – Module 9) ──────────────────
    # Independently re-checks the LLM's own answer: extracts its factual
    # claims, re-retrieves evidence FOR EACH CLAIM (not reusing the fused
    # context, which compression may have trimmed), verifies each claim
    # against that evidence, scores confidence, flags hallucinations, and
    # deterministically rewrites any claim that contradicts the evidence.
    verification: Optional[VerificationResult] = None
    if settings.verification_enabled:
        verification = verify_answer(db, answer_text, access_ctx, document_id=document_id)
        if verification.was_rewritten:
            logger.warning(
                "[RAG] ✏️ Answer rewritten | %d hallucinated claim(s) corrected.",
                len(verification.corrections),
            )
        answer_text = verification.final_answer

    # ─── Step 9: Build sources list for the response ──────────────────────────
    # Sourced from the FUSED chunks (what the LLM actually saw), not the raw
    # pre-fusion retrieval list.
    sources = []
    seen_doc_ids: set = set()
    for r in fused_results:
        doc_id = r.get("document_id") or r.get("metadata", {}).get("document_id", "unknown")
        sources.append({
            "document_id": doc_id,
            "chunk_index": r.get("chunk_index", r.get("metadata", {}).get("chunk_index")),
            "score": round(r.get("score", 0.0), 4),
            "text_preview": (r.get("text") or "")[:200] + (
                "…" if len(r.get("text") or "") > 200 else ""
            ),
        })
        seen_doc_ids.add(doc_id)

    latency_ms = (time.perf_counter() - started_at) * 1000

    logger.info(
        "[RAG] ✅ Pipeline complete | docs_cited=%d chunks_used=%d route=%s latency_ms=%.1f",
        len(seen_doc_ids), len(fused_results), retrieval.route.route, latency_ms,
    )

    # ─── Step 10: Query Log (Phase 12 – Module 10) ────────────────────────────
    # Store step of Continuous Learning: persists this query's routing/model/
    # confidence decisions and latency so Performance Metrics and Improve
    # Routing/Retrieval have telemetry to learn from once feedback arrives.
    if settings.query_logging_enabled:
        log_query(
            db,
            query_id=query_id,
            user_id=str(current_user.id),
            query_text=query,
            answer_text=answer_text,
            intent=analysis.intent.intent,
            complexity=analysis.complexity.level,
            route=retrieval.route.route,
            route_overridden="feedback_escalation" in retrieval.route.signals,
            model_used=generated.model_used,
            document_id_filter=document_id,
            confidence_score=verification.confidence_score if verification else None,
            is_grounded=generated.grounding.is_grounded,
            was_rewritten=verification.was_rewritten if verification else False,
            hallucinations_detected=len(verification.hallucinations) if verification else 0,
            retrieved_chunks=len(fused_results),
            latency_ms=latency_ms,
        )

    # ─── Step 11: Automatic Ticketing ─────────────────────────────────────────
    # A verification confidence below the dynamically configured administrator
    # threshold triggers automatic ticket generation and replaces the answer
    # with a safe user notification message.
    ticket = None
    ticket_user_message = None
    if verification is not None and verification.confidence_score is not None:
        from app.services.ticket_service import create_ticket_from_low_confidence, get_ticket_confidence_threshold
        
        configured_threshold = get_ticket_confidence_threshold(db)
        if verification.confidence_score < configured_threshold:
            ticket, ticket_user_message = create_ticket_from_low_confidence(
                db,
                query_id=query_id,
                user_id=str(current_user.id),
                original_question=query,
                generated_answer=answer_text,
                confidence_score=verification.confidence_score,
                confidence_threshold=configured_threshold,
                evidence=f"Verification confidence ({verification.confidence_score:.2f}) < threshold ({configured_threshold:.2f}). Claims: {verification.claims_total}, Hallucinations: {len(verification.hallucinations)}",
                source_document_ids=sorted(d for d in seen_doc_ids if d != "unknown"),
                intent=analysis.intent.intent,
                entities=analysis.entities,
            )
            if ticket_user_message:
                answer_text = ticket_user_message

    return {
        "answer": answer_text,
        "sources": sources,
        "total_indexed": store.total,
        "retrieved_chunks": len(fused_results),
        "query": query,
        "query_id": query_id,
        "query_analysis": analysis,
        "retrieval_route": retrieval.route,
        "context_fusion": fusion.stats,
        "model_used": generated.model_used,
        "provider": generated.provider,
        "grounding": generated.grounding,
        "verification": verification,
        "ticket": (
            {
                "id": str(ticket.id),
                "ticket_id": ticket.ticket_id,
                "domain": ticket.domain,
                "department": ticket.department,
                "status": ticket.status,
                "message": ticket_user_message,
            }
            if ticket is not None else None
        ),
        "latency_ms": round(latency_ms, 2),
    }
